repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: ^(oauth2_provider/migrations/|tests/migrations/)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.3
    hooks:
      - id: isort
        exclude: ^(oauth2_provider/migrations/|tests/migrations/)
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: ^(oauth2_provider/migrations/|tests/migrations/)
