# https://travis-ci.org/jazzband/django-oauth-toolkit
dist: bionic

language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install coveralls tox tox-travis

script:
  - tox

after_script:
  - coveralls
