language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source="oauth2_provider" runtests.py

after_success:
  - coveralls