# https://travis-ci.org/jazzband/django-oauth-toolkit
dist: xenial

language: python

python:
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install coveralls tox tox-travis

script:
  - tox

after_script:
  - coveralls
